spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true            # 하이버네이트가 DB에 날리는 모든 쿼리(DDL, DML)를 보여준다.
        format_sql: true          # sql 예쁘게 포맷팅
        use_sql_comments: true    # 추가적인 주석 표시